<a href="https://colab.research.google.com/github/Plluxury/XXX/blob/main/cr1_mo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('telecom_churn.csv')

In [ ]:
data

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
5,AL,118,510,Yes,No,0,223.4,98,37.98,220.6,101,18.75,203.9,118,9.18,6.3,6,1.70,0,False
6,MA,121,510,No,Yes,24,218.2,88,37.09,348.5,108,29.62,212.6,118,9.57,7.5,7,2.03,3,False
7,MO,147,415,Yes,No,0,157.0,79,26.69,103.1,94,8.76,211.8,96,9.53,7.1,6,1.92,0,False
8,LA,117,408,No,No,0,184.5,97,31.37,351.6,80,29.89,215.8,90,9.71,8.7,4,2.35,1,False
9,WV,141,415,Yes,Yes,37,258.6,84,43.96,222.0,111,18.87,326.4,97,14.69,11.2,5,3.02,0,False
10,IN,65,415,No,No,0,129.1,137,21.95,228.5,83,19.42,208.8,111,9.40,12.7,6,3.43,4,True
11,RI,74,415,No,No,0,187.7,127,31.91,163.4,148,13.89,196.0,94,8.82,9.1,5,2.46,0,False
12,IA,168,408,No,No,0,128.8,96,21.90,104.9,71,8.92,141.1,128,6.35,11.2,2,3.02,1,False
13,MT,95,510,No,No,0,156.6,88,26.62,247.6,75,21.05,192.3,115,8.65,12.3,5,3.32,3,False
14,IA,62,415,No,No,0,120.7,70,20.52,307.2,76,26.11,203.0,99,9.14,13.1,6,3.54,4,False
15,NY,161,415,No,No,0,332.9,67,56.59,317.8,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True
16,ID,85,408,No,Yes,27,196.4,139,33.39,280.9,90,23.88,89.3,75,4.02,13.8,4,3.73,1,False
17,VT,93,510,No,No,0,190.7,114,32.42,218.2,111,18.55,129.6,121,5.83,8.1,3,2.19,3,False
18,VA,76,510,No,Yes,33,189.7,66,32.25,212.8,65,18.09,165.7,108,7.46,10.0,5,2.70,1,False
19,TX,73,415,No,No,0,224.4,90,38.15,159.5,88,13.56,192.8,74,8.68,13.0,2,3.51,1,False
20,FL,147,415,No,No,0,155.1,117,26.37,239.7,93,20.37,208.8,133,9.40,10.6,4,2.86,0,False
21,CO,77,408,No,No,0,62.4,89,10.61,169.9,121,14.44,209.6,64,9.43,5.7,6,1.54,5,True
22,AZ,130,415,No,No,0,183.0,112,31.11,72.9,99,6.20,181.8,78,8.18,9.5,19,2.57,0,False
23,SC,111,415,No,No,0,110.4,103,18.77,137.3,102,11.67,189.6,105,8.53,7.7,6,2.08,2,False
24,VA,132,510,No,No,0,81.1,86,13.79,245.2,72,20.84,237.0,115,10.67,10.3,2,2.78,0,False
25,NE,174,415,No,No,0,124.3,76,21.13,277.1,112,23.55,250.7,115,11.28,15.5,5,4.19,3,False
26,WY,57,408,No,Yes,39,213.0,115,36.21,191.1,112,16.24,182.7,115,8.22,9.5,3,2.57,0,False
27,MT,54,408,No,No,0,134.3,73,22.83,155.5,100,13.22,102.1,68,4.59,14.7,4,3.97,3,False
28,MO,20,415,No,No,0,190.0,109,32.30,258.2,84,21.95,181.5,102,8.17,6.3,6,1.70,0,False
29,HI,49,510,No,No,0,119.3,117,20.28,215.1,109,18.28,178.7,90,8.04,11.1,1,3.00,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3303,WI,114,415,No,Yes,26,137.1,88,23.31,155.7,125,13.23,247.6,94,11.14,11.5,7,3.11,2,False
3304,IL,71,510,Yes,No,0,186.1,114,31.64,198.6,140,16.88,206.5,80,9.29,13.8,5,3.73,4,True
3305,IN,58,415,No,Yes,22,224.1,127,38.10,238.8,85,20.30,174.2,86,7.84,11.5,7,3.11,2,False
3306,AL,106,408,No,Yes,29,83.6,131,14.21,203.9,131,17.33,229.5,73,10.33,8.1,3,2.19,1,False
3307,OK,172,408,No,No,0,203.9,109,34.66,234.0,123,19.89,160.7,65,7.23,17.8,4,4.81,4,False
3308,IA,45,415,No,No,0,211.3,87,35.92,165.7,97,14.08,265.9,72,11.97,13.3,6,3.59,1,False
3309,VT,100,408,Yes,No,0,219.4,112,37.30,225.7,102,19.18,255.3,95,11.49,12.0,4,3.24,4,False
3310,NY,94,415,No,No,0,190.4,91,32.37,92.0,107,7.82,224.8,108,10.12,13.6,17,3.67,2,False
3311,LA,128,415,No,No,0,147.7,94,25.11,283.3,83,24.08,188.3,124,8.47,6.9,5,1.86,2,False
3312,SC,181,408,No,No,0,229.9,130,39.08,144.4,93,12.27,262.4,110,11.81,14.2,4,3.83,2,False
3313,ID,127,408,No,No,0,102.8,128,17.48,143.7,95,12.21,191.4,97,8.61,10.0,5,2.70,1,False
3314,MO,89,415,No,No,0,178.7,81,30.38,233.7,74,19.86,131.9,120,5.94,9.1,4,2.46,1,False
3315,ME,149,415,No,Yes,18,148.5,106,25.25,114.5,106,9.73,178.3,98,8.02,6.5,4,1.76,0,False
3316,MS,103,510,No,Yes,29,164.1,111,27.90,219.1,96,18.62,220.3,108,9.91,12.3,9,3.32,0,False
3317,SD,163,415,Yes,No,0,197.2,90,33.52,188.5,113,16.02,211.1,94,9.50,7.8,8,2.11,1,False
3318,OK,52,415,No,No,0,124.9,131,21.23,300.5,118,25.54,192.5,106,8.66,11.6,4,3.13,2,False
3319,WY,89,415,No,No,0,115.4,99,19.62,209.9,115,17.84,280.9,112,12.64,15.9,6,4.29,3,False
3320,GA,122,510,Yes,No,0,140.0,101,23.80,196.4,77,16.69,120.1,133,5.40,9.7,4,2.62,4,True
3321,VT,60,415,No,No,0,193.9,118,32.96,85.0,110,7.23,210.1,134,9.45,13.2,8,3.56,3,False
3322,MD,62,408,No,No,0,321.1,105,54.59,265.5,122,22.57,180.5,72,8.12,11.5,2,3.11,4,True
3323,IN,117,415,No,No,0,118.4,126,20.13,249.3,97,21.19,227.0,56,10.22,13.6,3,3.67,5,True
3324,WV,159,415,No,No,0,169.8,114,28.87,197.7,105,16.80,193.7,82,8.72,11.6,4,3.13,1,False
3325,OH,78,408,No,No,0,193.4,99,32.88,116.9,88,9.94,243.3,109,10.95,9.3,4,2.51,2,False
3326,OH,96,415,No,No,0,106.6,128,18.12,284.8,87,24.21,178.9,92,8.05,14.9,7,4.02,1,False
3327,SC,79,415,No,No,0,134.7,98,22.90,189.7,68,16.12,221.4,128,9.96,11.8,5,3.19,2,False
3328,AZ,192,415,No,Yes,36,156.2,77,26.55,215.5,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False
3329,WV,68,415,No,No,0,231.1,57,39.29,153.4,55,13.04,191.3,123,8.61,9.6,4,2.59,3,False
3330,RI,28,510,No,No,0,180.8,109,30.74,288.8,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False
3331,CT,184,510,Yes,No,0,213.8,105,36.35,159.6,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False
3332,TN,74,415,No,Yes,25,234.4,113,39.85,265.9,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False

In [ ]:
#Первое задание
len(data['State'].unique())

51

In [ ]:
#Второе задание
data['Account length'].mean()

101.06480648064806

In [ ]:
#Третье задание
a = data[['International plan','Churn']]
race = a[a['International plan']=='Yes']
race = race['Churn'] == True
race.value_counts(True)

False    0.575851
True     0.424149
Name: Churn, dtype: float64

In [ ]:
#Четвертое задание
a = data['Total day minutes']
print(a.mean(), a.std())

179.77509750975094 54.46738920237137

In [ ]:
#Пятое задание
w = data[data['Churn']== False]
if w['Total day minutes'].mean() > w['Total eve minutes'].mean():
    print(True)
else: print(False)

False

In [ ]:
#6
a = data['State'].unique()
for i in a:
    b = data[data['State']== i ]
    print(i, 'DM:',round(b['Total day minutes'].mean()), 'EM:',round(b['Total eve minutes'].mean()))

KS DM: 192.0 EM: 203.0
OH DM: 183.0 EM: 206.0
NJ DM: 196.0 EM: 198.0
OK DM: 180.0 EM: 193.0
AL DM: 186.0 EM: 195.0
MA DM: 180.0 EM: 215.0
MO DM: 171.0 EM: 200.0
LA DM: 178.0 EM: 198.0
WV DM: 174.0 EM: 188.0
IN DM: 197.0 EM: 203.0
RI DM: 167.0 EM: 211.0
IA DM: 178.0 EM: 206.0
MT DM: 174.0 EM: 202.0
NY DM: 175.0 EM: 197.0
ID DM: 179.0 EM: 195.0
VT DM: 182.0 EM: 205.0
VA DM: 177.0 EM: 204.0
TX DM: 182.0 EM: 200.0
FL DM: 180.0 EM: 210.0
CO DM: 179.0 EM: 207.0
AZ DM: 172.0 EM: 188.0
SC DM: 166.0 EM: 207.0
NE DM: 177.0 EM: 203.0
WY DM: 180.0 EM: 206.0
HI DM: 176.0 EM: 191.0
IL DM: 174.0 EM: 197.0
NH DM: 177.0 EM: 198.0
GA DM: 185.0 EM: 204.0
AK DM: 178.0 EM: 184.0
MD DM: 197.0 EM: 196.0
AR DM: 176.0 EM: 201.0
WI DM: 179.0 EM: 197.0
OR DM: 176.0 EM: 201.0
MI DM: 181.0 EM: 208.0
DE DM: 175.0 EM: 208.0
UT DM: 184.0 EM: 195.0
CA DM: 184.0 EM: 199.0
MN DM: 183.0 EM: 199.0
SD DM: 190.0 EM: 203.0
NC DM: 185.0 EM: 203.0
WA DM: 179.0 EM: 204.0
NM DM: 171.0 EM: 212.0
NV DM: 176.0 EM: 203.0
DC DM: 171.0 EM: 196.0
KY DM: 174.0 EM: 196.0
ME DM: 185.0 EM: 201.0
MS DM: 178.0 EM: 200.0
TN DM: 176.0 EM: 211.0
PA DM: 188.0 EM: 192.0
CT DM: 175.0 EM: 204.0
ND DM: 187.0 EM: 208.0

In [ ]:
#7
data_d = data[['Churn', 'International plan']]
data_d

      Churn International plan
0     False                 No
1     False                 No
2     False                 No
3     False                Yes
4     False                Yes
5     False                Yes
6     False                 No
7     False                Yes
8     False                 No
9     False                Yes
10     True                 No
11    False                 No
12    False                 No
13    False                 No
14    False                 No
15     True                 No
16    False                 No
17    False                 No
18    False                 No
19    False                 No
20    False                 No
21     True                 No
22    False                 No
23    False                 No
24    False                 No
25    False                 No
26    False                 No
27    False                 No
28    False                 No
29    False                 No
...     ...                ...
3303  False                 No
3304   True                Yes
3305  False                 No
3306  False                 No
3307  False                 No
3308  False                 No
3309  False                Yes
3310  False                 No
3311  False                 No
3312  False                 No
3313  False                 No
3314  False                 No
3315  False                 No
3316  False                 No
3317  False                Yes
3318  False                 No
3319  False                 No
3320   True                Yes
3321  False                 No
3322   True                 No
3323   True                 No
3324  False                 No
3325  False                 No
3326  False                 No
3327  False                 No
3328  False                 No
3329  False                 No
3330  False                 No
3331  False                Yes
3332  False                 No

[3333 rows x 2 columns]

In [ ]:
y = data_d[data_d['Churn']==True]
y = y['International plan'] == 'Yes'
y.value_counts(True)

False    0.716356
True     0.283644
Name: International plan, dtype: float64

In [ ]:
n = data_d[data_d['Churn']==False]
n = n['International plan'] == 'Yes'
n.value_counts(True)

False    0.934737
True     0.065263
Name: International plan, dtype: float64

In [ ]:
#8
data_d = data[['Total day minutes', 'Total eve minutes','Total night minutes']]

In [ ]:
data_d

      Total day minutes  Total eve minutes  Total night minutes
0                 265.1              197.4                244.7
1                 161.6              195.5                254.4
2                 243.4              121.2                162.6
3                 299.4               61.9                196.9
4                 166.7              148.3                186.9
5                 223.4              220.6                203.9
6                 218.2              348.5                212.6
7                 157.0              103.1                211.8
8                 184.5              351.6                215.8
9                 258.6              222.0                326.4
10                129.1              228.5                208.8
11                187.7              163.4                196.0
12                128.8              104.9                141.1
13                156.6              247.6                192.3
14                120.7              307.2                203.0
15                332.9              317.8                160.6
16                196.4              280.9                 89.3
17                190.7              218.2                129.6
18                189.7              212.8                165.7
19                224.4              159.5                192.8
20                155.1              239.7                208.8
21                 62.4              169.9                209.6
22                183.0               72.9                181.8
23                110.4              137.3                189.6
24                 81.1              245.2                237.0
25                124.3              277.1                250.7
26                213.0              191.1                182.7
27                134.3              155.5                102.1
28                190.0              258.2                181.5
29                119.3              215.1                178.7
...                 ...                ...                  ...
3303              137.1              155.7                247.6
3304              186.1              198.6                206.5
3305              224.1              238.8                174.2
3306               83.6              203.9                229.5
3307              203.9              234.0                160.7
3308              211.3              165.7                265.9
3309              219.4              225.7                255.3
3310              190.4               92.0                224.8
3311              147.7              283.3                188.3
3312              229.9              144.4                262.4
3313              102.8              143.7                191.4
3314              178.7              233.7                131.9
3315              148.5              114.5                178.3
3316              164.1              219.1                220.3
3317              197.2              188.5                211.1
3318              124.9              300.5                192.5
3319              115.4              209.9                280.9
3320              140.0              196.4                120.1
3321              193.9               85.0                210.1
3322              321.1              265.5                180.5
3323              118.4              249.3                227.0
3324              169.8              197.7                193.7
3325              193.4              116.9                243.3
3326              106.6              284.8                178.9
3327              134.7              189.7                221.4
3328              156.2              215.5                279.1
3329              231.1              153.4                191.3
3330              180.8              288.8                191.9
3331              213.8              159.6                139.2
3332              234.4              265.9                241.4

[3333 rows x 3 columns]

In [ ]:
q = round((sum(data_d['Total day minutes']) +sum(data_d['Total eve minutes'])  + sum(data_d['Total night minutes']))/3333,2)
q

581.63

In [ ]:
lenth = []
for i in range(3333):
    if data_d['Total day minutes'][i]+data_d['Total eve minutes'][i]+data_d['Total night minutes'][i]>q:
        lenth.append(1)
print('У',len(lenth),'человек больше минут')

У 1695 человек больше минут

In [ ]:
#9
data_d = data[['Churn', 'Customer service calls']]
data_d

      Churn  Customer service calls
0     False                       1
1     False                       1
2     False                       0
3     False                       2
4     False                       3
5     False                       0
6     False                       3
7     False                       0
8     False                       1
9     False                       0
10     True                       4
11    False                       0
12    False                       1
13    False                       3
14    False                       4
15     True                       4
16    False                       1
17    False                       3
18    False                       1
19    False                       1
20    False                       0
21     True                       5
22    False                       0
23    False                       2
24    False                       0
25    False                       3
26    False                       0
27    False                       3
28    False                       0
29    False                       1
...     ...                     ...
3303  False                       2
3304   True                       4
3305  False                       2
3306  False                       1
3307  False                       4
3308  False                       1
3309  False                       4
3310  False                       2
3311  False                       2
3312  False                       2
3313  False                       1
3314  False                       1
3315  False                       0
3316  False                       0
3317  False                       1
3318  False                       2
3319  False                       3
3320   True                       4
3321  False                       3
3322   True                       4
3323   True                       5
3324  False                       1
3325  False                       2
3326  False                       1
3327  False                       2
3328  False                       2
3329  False                       3
3330  False                       2
3331  False                       2
3332  False                       0

[3333 rows x 2 columns]

In [ ]:
y = data_d[data_d['Churn']==True]
round(y['Customer service calls'].mean(), 2)

2.23

In [ ]:
n = data_d[data_d['Churn']==False]
round(n['Customer service calls'].mean(), 2)

1.45